### PR TITLE
Add os matrix containing macos, windows and ubuntu to github workflows

### PR DESCRIPTION
**Pull request by nrobi144**

### CODE REVIEW

**Review by Alex009 — CHANGES_REQUESTED** [review]
we can't use this publish way, because all 3 platforms will be publish common, android artifacts

**Comment by Alex009** [comment]
https://github.com/korlibs/klock/blob/master/.github/workflows/DEPLOY.yml here good sample of publish i think.
for windows target do only publish windows task, for linux common and linux publish task, and for macos all others except common

**Comment by nrobi144** [comment]
@Alex009 as the korlibs example, they are using `actuallyPublishBintray` which essentially marks the uploaded artifacts as published. We could add a dependency to [easy-kotlin-mpp-gradle-plugin](https://korlibs.soywiz.com/internals) and do the same, or implement some alternative.

I've added a possible solution from the [official docs](https://kotlinlang.org/docs/reference/mpp-publish-lib.html#avoid-duplicate-publications) to avoid duplicates, though it still needs to be tested

**Review by Alex009 — APPROVED** [review]

**Comment by Alex009** [comment]
thx! will try it

**Pull request merged**
