### PR TITLE
Feature/support all kotlin targets

### PR DESCRIPTION
**Pull request by nrobi144**

### CODE REVIEW

**Review by Alex009 — CHANGES_REQUESTED** [review]
need to fix ci errors
```
> Task :sample:android-app:validateSigningDebug
e: /Users/runner/work/moko-parcelize/moko-parcelize/parcelize/src/androidMain/kotlin/dev/icerock/moko/parcelize/Parcelize.kt: (13, 18): Redeclaration: Parcelable

e: /Users/runner/work/moko-parcelize/moko-parcelize/parcelize/src/commonMain/kotlin/dev/icerock/moko/parcelize/Parcelize.kt: (11, 18): Interface 'Parcelable' has several compatible actual declarations in modules <parcelize_debug>, <parcelize_debug>
> Task :parcelize:compileDebugKotlinAndroid FAILED
e: /Users/runner/work/moko-parcelize/moko-parcelize/parcelize/src/commonMain/kotlin/dev/icerock/moko/parcelize/Parcelize.kt: (11, 18): Redeclaration: Parcelable
e: /Users/runner/work/moko-parcelize/moko-parcelize/parcelize/src/notAndroidMain/kotlin/dev/icerock/moko/parcelize/Parcelize.kt: (7, 18): Redeclaration: Parcelable
```

**Comment by nrobi144** [comment]
@Alex009 , yepp, unfortunately I didn't find a way to avoid explicitly configuring every sourceSet
Any ideas?

**Comment by Alex009** [comment]
@nrobi144 i think we can use all with name.startWith:
```
val nonAndroidPrefixes = listOf("ios", "macos", "linux", ...)
sourceSets.matching { sourceSet ->
    nonAndroidPrefixes.any { sourceSet.name.startWith(it) }
 }.all {
  ...
}
```

**Comment by nrobi144** [comment]
> @nrobi144 i think we can use all with name.startWith:
> 
> ```
> val nonAndroidPrefixes = listOf("ios", "macos", "linux", ...)
> sourceSets.matching { sourceSet ->
>     nonAndroidPrefixes.any { sourceSet.name.startWith(it) }
>  }.all {
>   ...
> }
> ```

@Alex009 that's right, but I was thinking of reusing the created targets.
For ex the ios, windows & linux could return a `listOf<KotlinNativeTarget>`, would be cool to tie the configuration to that list

**Review by Alex009 — APPROVED** [review]

**Pull request merged**
